default_url_options:
  host: qikup.ru
  port: 80

smtp_settings:
  host: localhost
  port: 25

deliver_settings:
  from: noreply@qikup.ru

application:
  title: WORKSOFT
  description: Магазин 1С-приложений
  author: Александр Шальнов и Данил Письменный
  realm: WORKSOFT
