default_url_options:
  host: worksoft.ru
  port: 80

app:
  title: WORKSOFT

smtp_settings:
  host: localhost
  port: 25

deliver_settings:
  from: noreply@worksoft.ru

application:
  title: WORKSOFT
  description: Магазин 1С-приложений
  author: Александр Шальнов и Данил Письменный
  realm: WORKSOFT
