default_url_options:
  host: localhost
  port: 40009

# хранить в test.local.yml
# Порты распределяются тут http://wiki.brandymint.ru/wiki/%D0%A2%D0%B5%D1%81%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5
capybara:
  port: 40009
